from custom_constants import *
from pdf2image import convert_from_path
from PIL import ImageDraw
from typing import List, Tuple, Dict

import numpy as np
import cv2


def process_pdf_with_dots(
    input_pdf: str,
    output_pdf: str = output_dot_pdf_file,
    coordinates_file: str = dots_coordinates_file,
    y_threshold: int = y_distance_threshold,
    dot_color: Tuple[int, int, int] = (255, 0, 0),
    dot_radius: int = radius_of_the_dot
) -> None:
    """
    Detects dark areas in a PDF, marks them with colored dots, groups them by Y-coordinate proximity,
    and saves both the annotated PDF and coordinate data.

    Args:
        input_pdf (str): Path to the input PDF file.
        output_pdf (str): Path to save the output PDF with dots.
        coordinates_file (str): Path to save grouped coordinates in plain text.
        y_threshold (int): Y-distance threshold for grouping dots into lines.
        dot_color (Tuple[int, int, int]): RGB color for drawing dots.
        dot_radius (int): Radius (in pixels) of the drawn dots.

    Side Effects:
        - Saves visual PDF with dots.
        - Saves text file with grouped coordinates.
        - Prints debug info to stdout.
    """

    pages = convert_from_path(input_pdf, dpi=dpi_for_pages)
    processed_images = []
    all_coordinates = []

    for page_number, page in enumerate(pages, 1):
        img_cv = np.array(page.convert(color_format))
        img_cv = cv2.cvtColor(img_cv, cv2.COLOR_RGB2BGR)
        gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
        _, thresh = cv2.threshold(gray, binarize_threshold, 255, cv2.THRESH_BINARY_INV)
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        draw = ImageDraw.Draw(page)
        coords = []

        for cnt in contours:
            M = cv2.moments(cnt)
            if M["m00"] != 0:
                cx = int(M["m10"] / M["m00"])
                cy = int(M["m01"] / M["m00"])
                draw.ellipse(
                    (cx - dot_radius, cy - dot_radius, cx + dot_radius, cy + dot_radius),
                    fill=dot_color
                )
                coords.append((cx, cy))

        coords.sort(key=lambda c: c[1])
        grouped_lines = group_by_y(coords, y_threshold)
        all_coordinates.append((page_number, grouped_lines))
        processed_images.append(page)

    processed_images[0].save(output_pdf, save_all=True, append_images=processed_images[1:])

    with open(coordinates_file, "w") as file:
        for page_number, lines in all_coordinates:
            file.write(f"Page {page_number}:\n")
            for idx, line in enumerate(lines, 1):
                avg_y = sum(dot[1] for dot in line) / len(line)
                marker = "*" if len(line) == 1 else ""
                file.write(f"  Line {idx}: Average y = {avg_y:.2f}{marker}\n")
                for i, (x, y) in enumerate(line, 1):
                    file.write(f"    Dot {i}: (x={x}, y={y})\n")
            file.write("\n")


def group_by_y(coords: List[Tuple[int, int]], y_threshold: int) -> List[List[Tuple[int, int]]]:
    """
    Groups dots into horizontal lines based on vertical distance (Y-axis proximity).

    Args:
        coords (List[Tuple[int, int]]): List of (x, y) tuples.
        y_threshold (int): Max vertical gap to consider dots as part of the same line.

    Returns:
        List[List[Tuple[int, int]]]: Grouped dot lines.
    """

    lines = []
    current_line = []
    last_y = None

    for coord in coords:
        if last_y is None or abs(coord[1] - last_y) <= y_threshold:
            current_line.append(coord)
        else:
            lines.append(current_line)
            current_line = [coord]
        last_y = coord[1]

    if current_line:
        lines.append(current_line)

    return lines


def parse_coordinates(file_path: str) -> List[Dict]:
    """
    Parses grouped coordinate lines from a .txt file generated by `process_pdf_with_dots`.

    Args:
        file_path (str): Path to the grouped coordinate file.

    Returns:
        List[Dict]: Each dict has 'average_y' and list of 'dots'.

    Side Effects:
        - Logs parsing errors to stdout.
        - Prints parsed result.
    """

    result = []
    line_data = None

    try:
        with open(file_path, 'r', encoding=encoding_format) as file:
            for line in file:
                line = line.strip()

                if "Average y" in line:
                    if line_data:
                        result.append(line_data)
                    try:
                        avg_y = float(line.split("Average y = ")[1].split("*")[0].strip())
                        line_data = {'average_y': avg_y, 'dots': []}
                    except Exception:
                        line_data = {'average_y': 0.0, 'dots': []}

                elif "Dot" in line and line_data is not None:
                    try:
                        x, y = map(lambda s: int(s.split('=')[1]), line.split("(")[1].split(")")[0].split(","))
                        line_data['dots'].append((x, y))
                    except Exception:
                        continue

            if line_data:
                result.append(line_data)

    except FileNotFoundError:
        RuntimeError(f"File not found: {file_path}")
    except Exception as e:
        RuntimeError(f"Failed to read {file_path}: {e}")

    return result


def compare_files(file_1: str, file_2: str, threshold: float = 1e-5, max_lines_to_compare: int = max_lines_to_compare_param) -> bool:
    """
    Compares average Y-values of grouped lines between two coordinate files.

    Args:
        file_1 (str): First coordinate file.
        file_2 (str): Second coordinate file.
        threshold (float): Max allowed diff between average Y values.
        max_lines_to_compare (int): Number of lines from top to compare.

    Returns:
        bool: True if all lines match within threshold, otherwise False.
    """

    data_1 = parse_coordinates(file_1)
    data_2 = parse_coordinates(file_2)

    if not data_1 or not data_2:
        RuntimeError("⚠️ No data to compare.")
        return True

    if len(data_1) < max_lines_to_compare or len(data_2) < max_lines_to_compare:
        RuntimeError("⚠️ Not enough lines to compare.")
        return True

    all_match = True

    for i, (line1, line2) in enumerate(zip(data_1, data_2), 1):
        if i > max_lines_to_compare:
            break
        if (abs(line1['average_y'] - line2['average_y'])) > threshold:
            all_match = False

    return all_match
